# Generated by Django 4.0.4 on 2022-05-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_perguntas', models.CharField(max_length=255)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almoxarifado.pergunta')),
            ],
        ),
    ]
