# Generated by Django 4.0.4 on 2022-05-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0002_rename_texto_perguntas_alternativa_texto_alternativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='texto_alternativa',
            new_name='texto_perguntas',
        ),
    ]
