# Generated by Django 4.0.4 on 2022-05-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0003_rename_texto_alternativa_alternativa_texto_perguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_desc', models.TextField(max_length=10000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almoxarifado.pergunta')),
            ],
        ),
    ]
