# Generated by Django 4.0.4 on 2022-05-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0005_rename_question_descricao_pergunta_descricao2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descricao2',
            old_name='twxto_mun',
            new_name='texto_mun',
        ),
    ]
