# Generated by Django 4.0.4 on 2022-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0006_rename_twxto_mun_descricao2_texto_mun'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
