# Generated by Django 4.0.4 on 2022-05-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0007_alternativa_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='calibre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Almoxarifado.alternativa'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='votos2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descricao2',
            name='calibre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Almoxarifado.alternativa'),
        ),
        migrations.AddField(
            model_name='descricao2',
            name='votos3',
            field=models.IntegerField(default=0),
        ),
    ]
