# Generated by Django 4.0.4 on 2022-05-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almoxarifado', '0008_descricao_calibre_descricao_votos2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='votos',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='votos2',
        ),
        migrations.RemoveField(
            model_name='descricao2',
            name='votos3',
        ),
    ]
